# MIT License
#
# Copyright (c) 2020 Aleksandr Kotlyar
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

image: python:3.7.6-alpine
stages:
  - test

variables:
  BROWSER: chrome

.job_template:
  before_script:
    - pip3 install -r requirements.txt
  script:
    - pytest --browser=$BROWSER --local='false'

e2e:remote:chrome:
  extends: .job_template
  services:
    - selenium/standalone-chrome
  only:
    variables:
      - $BROWSER == 'chrome'

e2e:remote:firefox:
  extends: .job_template
  services:
    - selenium/standalone-firefox
  only:
    variables:
      - $BROWSER == 'firefox'

e2e:remote:opera:
  extends: .job_template
  services:
    - selenium/standalone-opera
  only:
    variables:
      - $BROWSER == 'opera'